### ISSUE TITLE
fork option

### ISSUE THREAD

**Issue by Ataurr** [mosinski/gumsnipp#1]
It will be great if you add fork option in snippet like bootsnipp

**Comment by mosinski** [comment]
That's really a good idea, and it shouldn't be difficult to implement.
I'll start working on it..

**Comment by xperter** [comment]
:+1: Great

**Comment by mosinski** [comment]
I've just added new fork options to the application.
You can check code on new branch: 
https://github.com/mosinski/gumsnipp/tree/fork-option

Of course I also update the app on http://gumsnipp.com

If You have any comments or discover any bugs let me know
Cheers :bowtie:

**Comment by Ataurr** [comment]
Thats great news.

You are using a tool for pagepeeker i think if you use this one it will be great https://github.com/msurguy/snipsnap
pagepeeker text showing on bottom every snippet image.

Thanks

**Comment by Ataurr** [comment]
Signup with github not work here. http://puu.sh/lwIlp/0e0f3905b5.png

**Comment by mosinski** [comment]
thanks :+1: 
Just fixed this issue :smiley:
